openapi: 3.0.0
info:
  title: PDS外部非公開API仕様書
  version: 2.0.0
servers:
  - url: https://{pdsSubDomain}.{tdcDomain}/
    description: |
      プロダクション API<br>
      - pdsSubDomain：PDSサブドメイン<br>
      - tdcDomain：板橋ドメイン
    variables:
      pdsSubDomain:
        default: XXXX
      tdcDomain:
        default: XXXX
  - url: http://{host}:{port}/
    description: 開発用
    variables:
      host:
        default: localhost
      port:
        default: '8000'
paths:
  /api/2.0/tfoperator/regist:
    $ref: ./paths/tfoperator/registTfOperator.yaml
  /api/2.0/tfoperator/search:
    $ref: ./paths/tfoperator/searchTfOperator.yaml
  /api/2.0/tfoperator/delete:
    $ref: ./paths/tfoperator/deleteTfOperator.yaml
  /api/2.0/tfoperator/login:
    $ref: ./paths/tfoperator/loginTfOperator.yaml
  /api/2.0/tfoperator/changepassword:
    $ref: ./paths/tfoperator/changePasswordTfOperator.yaml
  /api/2.0/tfoperator/resetpassword:
    $ref: ./paths/tfoperator/resetPasswordTfOperator.yaml
  /api/2.0/pdsuser/regist:
    $ref: ./paths/pdsuser/registPdsUser.yaml
  /api/2.0/pdsuser/search:
    $ref: ./paths/pdsuser/getPdsUser.yaml
  /api/2.0/pdsuser/update:
    $ref: ./paths/pdsuser/updatePdsUser.yaml
  /api/2.0/pdsuser/disable:
    $ref: ./paths/pdsuser/disablePdsUser.yaml
  /api/2.0/pdsuser/generate:
    $ref: ./paths/pdsuser/generateKeyPair.yaml
  /api/2.0/pdsuser/getUseCount:
    $ref: ./paths/pdsuser/getUseCount.yaml
  /api/2.0/pdsuser/getAccessRecord:
    $ref: ./paths/pdsuser/getAccessRecord.yaml
  /api/2.0/transaction/multiDownload:
    $ref: ./paths/transaction/multiDownload.yaml
  /api/2.0/transaction/download/status:
    $ref: ./paths/transaction/getDownloadstatus.yaml
  /api/2.0/transaction/multidelete:
    $ref: ./paths/transaction/multidelete.yaml
  /api/2.0/transaction/search/{pageNo}:
    $ref: ./paths/transaction/searchUser.yaml
components:
  securitySchemes:
    AccessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        ### ・アクセストークン概要
        アクセストークンは初回実行時はTFオペレータログインAPIにより発行される。<br>
        アクセストークンはログイン画面以降のすべての機能の認証に利用される。<br>
        ※ペイロード内部のTFオペレータパスワードリセットフラグがtrueのアクセストークンが発行された場合、<br>　TFオペレータパスワードリセット画面のみの遷移に制限される。<br>
        アクセストークン取得後に画面からAPIを実行する作業を実行すると有効期限を更新した新しいアクセストークンがAPIから返却される。<br>
        アクセストークンの有効期限は30分。

        ### ・JWTの概要
        ヘッダ、ペイロード、署名の3つから成る。<br>
        ペイロードは伝達する情報の本体で、システムが必要とするデータを任意に指定することができる。

        ### ・ペイロード構成
        |項目物理名|項目論理名|備考|
        |------------|----------|----|
        |tfOperatorId|TFオペレータID||
        |tfOperatorName|TFオペレータ名||
        |accessToken|アクセストークン||
        |tfOperatorPasswordResetFlg|TFオペレータパスワードリセットフラグ|trueの場合には、TFオペレータパスワード変更画面のみ遷移可能。|
        |exp|有効期限|JWT規定の有効期限。<br>30分有効。|

        ### ・ペイロードの一例
        ```
        {
          "tfOperatorId": "A000001"
          "tfOperatorName": "山田 太郎"
          "accessToken": "9886446D27D148B24E7D66751EAF81143B3F2C81CBBF3E58465F8836DBF6C3C7556D1141F22B692C4164A4E59C2EDDF3988E17889F091AF82DE8D7555F27806215AFB7AF21E9D72A392413A54A09C4B5834A6CB4D9A5D12214CB84B76E6DA47164D27460"
          "tfOperatorPasswordResetFlg": true
          "exp": "2022/01/01 12:34:56.789"
        }
        ```
        #### リクエストヘッダ情報
        <table>
            <tr>
              <td><b>Security Scheme Type</b></td>
              <td>HTTP</td>
            </tr>
            <tr>
              <td><b>HTTP Authorization Scheme</b></td>
              <td>bearer</td>
            </tr>
            <tr>
              <td><b>Bearer format</b></td>
              <td>"JWT"</td>
            </tr>
        </table>

        #### レスポンスヘッダ情報
tags:
  - name: tfoperator
    description: TFオペレータに関するAPI群
  - name: pdsuser
    description: PDSユーザに関するAPI群
  - name: transaction
    description: 個人情報に関するAPI群
